from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd


def markdown_table(frame: pd.DataFrame) -> str:
    cols = list(frame.columns)
    rows = ["| " + " | ".join(cols) + " |", "| " + " | ".join(["---"] * len(cols)) + " |"]
    for _, row in frame.iterrows():
        values = []
        for value in row:
            if isinstance(value, float):
                values.append(f"{value:.4f}")
            else:
                values.append(str(value))
        rows.append("| " + " | ".join(values) + " |")
    return "\n".join(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifacts", default="artifacts_real")
    parser.add_argument("--output", default="docs/real_results.md")
    args = parser.parse_args()

    root = Path(args.artifacts)
    metrics = pd.read_csv(root / "real_model_metrics.csv")
    history = pd.read_csv(root / "real_history_ablation.csv")
    subgroup = pd.read_csv(root / "real_subgroup_metrics.csv")
    controls_path = root / "real_sequence_controls.csv"
    controls = pd.read_csv(controls_path) if controls_path.exists() else pd.DataFrame()
    summary = json.loads((root / "real_summary.json").read_text(encoding="utf-8"))

    latest = metrics.loc[metrics["model"] == "Logistic latest month"].iloc[0]
    full = metrics.loc[metrics["model"] == "Logistic full history"].iloc[0]
    history_delta = float(full.roc_auc - latest.roc_auc)

    decision = (
        "The six-month history has measurable incremental value over a latest-month-only "
        "logistic model. A deep sequence model should advance only if it beats the strongest "
        "tabular baseline under the same folds and improves calibration or fixed-capacity capture."
        if history_delta > 0.002
        else
        "The six-month history does not show a large stable gain over the latest-month baseline. "
        "A deep sequence model is not justified by this benchmark alone."
    )

    control_section = ""
    if not controls.empty:
        control_section = f"""
## Sequence-order controls

These tabular controls provide a reference for later LSTM, TCN and Transformer tests. A neural sequence model must show that order-sensitive inputs add value beyond the same monthly values in a flattened representation.

{markdown_table(controls)}
"""

    text = f"""# Real-data benchmark results

This report is generated by GitHub Actions from the official UCI **Default of Credit Card Clients** dataset. The dataset contains {summary['n_customers']:,} customers and has a default rate of {summary['default_rate']:.2%}.

## Executive result

- Best cross-validated model: **{summary['best_model']}**
- Best ROC AUC: **{summary['best_roc_auc']:.4f}**
- Full-history minus latest-month logistic ROC AUC: **{history_delta:+.4f}**
- Validation: {summary['validation']}
- Release decision: {summary['release_decision']}

**Decision:** {decision}

## Model comparison

{markdown_table(metrics)}

## History-length test

{markdown_table(history)}
{control_section}
## Audit groups

{markdown_table(subgroup)}

## Interpretation limits

The source has no application timestamp, policy decision, interest rate, loss-given-default, treatment assignment, UK geography, or rejected-applicant outcome. Therefore, this benchmark cannot establish temporal robustness, business profit, intervention benefit, UK fairness, or production readiness. Those remain explicit release gates.
"""
    Path(args.output).write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
